### ISSUE TITLE
404 on /lib/system.js

### ISSUE THREAD

**Issue by staxmanade** [shidhincr/react-jest-gulp-jspm-seed#1]
Hey,

This repo looks interesting. Giving it a spin...

I notice when testing it out that we're getting 404's for `/lib/system.js` (https://github.com/shidhincr/react-jest-gulp-jspm-seed/blob/master/index.html#L6)

Is that necessary since the `jspm_packages/system.js` is also being loaded?

**Comment by shidhincr** [comment]
Thanks @staxmanade .. I initially added the `lib/system.js` and later forgot to remove. Since the `jspm_packages/system.js` is there, the `lib/system.js` can be removed.

**Comment by staxmanade** [comment]
also, (not super familiar with jspm yet) but besides `npm install` do you have to `jspm install`?

**Comment by shidhincr** [comment]
`jspm install` is required, but I included that in the npm **postinstall** script. So once the npm install is finished, it should take care of it.

https://github.com/shidhincr/react-jest-gulp-jspm-seed/blob/master/package.json#L8

**Comment by staxmanade** [comment]
Ahh, thanks!
