### ISSUE TITLE
Getting typeError after gulp test

### ISSUE THREAD

**Issue by santosh9818** [shidhincr/react-jest-gulp-jspm-seed#3]
C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react-jest-gulp-
jspm-seed-master>gulp test
[16:02:10] Using gulpfile ~\Downloads\react-jest-gulp-jspm-seed-master\react-jes
t-gulp-jspm-seed-master\gulpfile.js
[16:02:10] Starting 'test'...
[16:02:10] Starting 'jest'...
[16:02:10] Finished 'test' after 29 ms

> react-jest-gulp-seed@1.0.0 test C:\Users\Daffodil-32\Downloads\react-jest-gulp
> -jspm-seed-master\react-jest-gulp-jspm-seed-master
> jest

Using Jest CLI v0.4.19
Waiting on 1 test...
 FAIL  **tests**\testComponent-spec.js (0.243s)
● Accordion › it encountered a declaration exception
- TypeError: C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\r
  eact-jest-gulp-jspm-seed-master\node_modules\react\addons.js: C:\Users\Daffodil-
  32\Downloads\react-jest-gulp-jspm-seed-master\react-jest-gulp-jspm-seed-master\n
  ode_modules\react\lib\ReactWithAddons.js: C:\Users\Daffodil-32\Downloads\react-j
  est-gulp-jspm-seed-master\react-jest-gulp-jspm-seed-master\node_modules\react\li
  b\LinkedStateMixin.js: C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-
  master\react-jest-gulp-jspm-seed-master\node_modules\react\lib\ReactLink.js: C:\
  Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react-jest-gulp-jsp
  m-seed-master\node_modules\react\lib\React.js: C:\Users\Daffodil-32\Downloads\re
  act-jest-gulp-jspm-seed-master\react-jest-gulp-jspm-seed-master\node_modules\rea
  ct\lib\ReactComponent.js: C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-se
  ed-master\react-jest-gulp-jspm-seed-master\node_modules\react\lib\ReactUpdateQue
  ue.js: C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react-jes
  t-gulp-jspm-seed-master\node_modules\react\lib\ReactUpdates.js: CallbackQueue.ge
  tPooled is not a function
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\lib\ReactUpdates.js:26:39
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\lib\ReactUpdateQueue.js:18:20
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\lib\ReactComponent.js:14:24
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\lib\React.js:18:22
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\lib\ReactLink.js:38:13
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\lib\LinkedStateMixin.js:15:17
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\lib\ReactWithAddons.js:21:24
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master\node_modules\react\addons.js:1:85
      at Suite.<anonymous> (C:\Users\Daffodil-32\Downloads\react-jest-gulp-jsp
  m-seed-master\react-jest-gulp-jspm-seed-master__tests__\testComponent-spec.js:4
  :15)
      at env.describe_ (<anonymous>:40:25)
      at env.describe (<anonymous>:27:19)
      at describe (C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-ma
  ster\react-jest-gulp-jspm-seed-master\node_modules\jest-cli\vendor\jasmine\jasmi
  ne-1.3.0.js:604:27)
      at C:\Users\Daffodil-32\Downloads\react-jest-gulp-jspm-seed-master\react
  -jest-gulp-jspm-seed-master__tests__\testComponent-spec.js:3:1
  1 test failed, 0 tests passed (1 total)
  Run time: 0.7s
  npm ERR! Test failed.  See above for more details.
  [16:02:14] Finished 'jest' after 4.19 s

**Comment by shidhincr** [comment]
Issue is fixed in #4

**Comment by shidhincr** [comment]
@santosh9818 Could you please check and let me know ?
